name: Release API

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE_NAME: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/core_api/prod

jobs:
  push:
    name: Push to GCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_DEVOPS_SA_KEY }}
          export_default_credentials: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Create Release Tag
        run: |
          # タグから最新のリリース番号を取得
          latest_release_num=`git tag | sed "s/^v//" | sort -n | tail -n1`
          # 初期リリースを考慮
          if [ $release_num = "" ]; then
            latest_release_num=0
          fi
          # 新しいリリースタグを作成
          new_release_tag=v`expr $latest_release_num + 1`
          git tag $new_release_tag
          git push origin $new_release_tag
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build Image and Push
        run: |
          # 最新のリリースタグを取得
          release_tag=`git tag | sort -n | tail -n1`
          image="$IMAGE_NAME:$release_tag"
          docker build -t $image .
          docker push $image
